version: '3.8'

services:
  svc:
    build: .
    ports:
      - "8888:8888"
  
  tester:
    image: golang:1.21
    working_dir: /tests
    volumes:
      - .:/tests
    depends_on:
      - svc
    entrypoint: ["sh", "-c", "sleep 2 && go test -v function_test.go"]
