name: FT - svc-ft-test01

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  function-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Compose Build and Run
        run: docker compose up --build --exit-code-from tester
